name: continuous-integration-foo

on:
    pull_request:
        branches:
            = master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Build with Gradle!
              working-directory: ./src/Platform
              run: ./gradlew build -x test

            - name: Run tests
              working-directory: .
              run: ./gradlew test

    system-test:
	runs-on: ubuntu-latest
	needs: build-and-test # make sure unit testing is run first
	steps:
	    - uses:
		actions/checkout@v1

	    - name: Start docker server
	      working-directory: .
	      run: docker-compose up -d --build

	    - name: Set up Python 3.7
	      uses: actions/setup-python@v1
	      with:
		python-version: '3.X'

	    - name: Install dependencies
	      working-directory: .
	      run: |
		pip3 install -U requests && pip3 install -U pytest

	    - name: Test with pytest
	      working-directory: .
	      run: pytest

	    - name: Stop docker server
	      working-directory: .
	      run: docker-compose down
